// 此檔由 scripts/generate-icon-data.mjs 自動產生，請勿手動編輯。
export const iconNames = [
  "button-add",
  "button-add-blue",
  "button-add-gray",
  "button-arrowdown",
  "button-arrowdown-white",
  "button-arrowup-white",
  "button-clear-white-v3",
  "button-download",
  "button-download-disable",
  "button-edit",
  "button-log",
  "button-log-disable",
  "button-magnifier",
  "button-more-white-v3",
  "button-new-tab",
  "button-new-tab-disable",
  "button-output",
  "button-pile-edit",
  "button-refresh",
  "button-refresh-disable",
  "button-remove",
  "button-search-white-v3",
  "button-settings",
  "button-success",
  "button-trashcan",
  "icon-add",
  "icon-chevron",
  "icon-close",
  "icon-delete",
  "icon-delete-disable",
  "icon-edit",
  "icon-edit-disable",
  "icon-locale-disable",
  "icon-locale-hover",
  "icon-locale-normal",
  "icon-save",
  "tooltip-info"
] as const

// Tailwind safelist（被 style.css 的 @source 掃描）：
// i-button-add i-button-add-mask i-button-add-blue i-button-add-blue-mask i-button-add-gray i-button-add-gray-mask i-button-arrowdown i-button-arrowdown-mask i-button-arrowdown-white i-button-arrowdown-white-mask i-button-arrowup-white i-button-arrowup-white-mask i-button-clear-white-v3 i-button-clear-white-v3-mask i-button-download i-button-download-mask i-button-download-disable i-button-download-disable-mask i-button-edit i-button-edit-mask i-button-log i-button-log-mask i-button-log-disable i-button-log-disable-mask i-button-magnifier i-button-magnifier-mask i-button-more-white-v3 i-button-more-white-v3-mask i-button-new-tab i-button-new-tab-mask i-button-new-tab-disable i-button-new-tab-disable-mask i-button-output i-button-output-mask i-button-pile-edit i-button-pile-edit-mask i-button-refresh i-button-refresh-mask i-button-refresh-disable i-button-refresh-disable-mask i-button-remove i-button-remove-mask i-button-search-white-v3 i-button-search-white-v3-mask i-button-settings i-button-settings-mask i-button-success i-button-success-mask i-button-trashcan i-button-trashcan-mask i-icon-add i-icon-add-mask i-icon-chevron i-icon-chevron-mask i-icon-close i-icon-close-mask i-icon-delete i-icon-delete-mask i-icon-delete-disable i-icon-delete-disable-mask i-icon-edit i-icon-edit-mask i-icon-edit-disable i-icon-edit-disable-mask i-icon-locale-disable i-icon-locale-disable-mask i-icon-locale-hover i-icon-locale-hover-mask i-icon-locale-normal i-icon-locale-normal-mask i-icon-save i-icon-save-mask i-tooltip-info i-tooltip-info-mask
